name: Convert CSV to JSON

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Explicitly allow write permissions to the repository

jobs:
  csv-to-json:
    if: startsWith(github.event.head_commit.message, '[refresh]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g csvtojson
          echo '{
            "type": "module"
          }' > package.json

      - name: Convert CSV to JSON
        run: |
          csvtojson data.csv > temp.json

      - name: Add "S" before signal numbers
        run: |
          node -e "
          import fs from 'fs';
          const data = JSON.parse(fs.readFileSync('temp.json', 'utf-8'));
          const updated = data.map(entry => {
            for (const key in entry) {
              if (key.toLowerCase().includes('signal') && entry[key]) {
                entry[key] = 'S' + entry[key];
              }
            }
            return entry;
          });
          fs.writeFileSync('data.json', JSON.stringify(updated, null, 2));
          "
      
      - name: Commit and push JSON file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add data.json
          git commit -m "[generated] ${GITHUB_EVENT_HEAD_COMMIT_MESSAGE#[refresh]}"
          git push
